---
netunicorn.ssh.private_key_location: "~/.ssh/id_rsa"  # path to SSH private key file
netunicorn.ssh.hosts:
  localhost: # name of the host (all names should be unique)
    address: "127.0.0.1"  # DNS name or IP address, required
    port: 22  # SSH port, default is 22
    username: "ubuntu"  # SSH username, required
    properties:
      os: "linux"  # OS type
      architecture: "amd64"  # CPU architecture
      netunicorn-environments: ['DockerImage', 'ShellExecution']
      custom-tag: "custom-value"  # custom tags

  some-another-host:
    address: "8.8.8.8"
    port: 22
    username: "rootGoogle"
    properties:
      os: "linux"
      architecture: "amd64"
      netunicorn-environments: ['ShellExecution']  # DockerImage is not supported
      custom-tag-2: "custom-value-2"